site_name: NKR Schema
site_description: Schema documentation for NKR
site_url: https://techlib.github.io/NKR-schema/
repo_url: https://github.com/techlib/NKR-schema
repo_name: techlib/NKR-schema

theme:
  name: material
  language: en
  palette:
    scheme: default
    primary: custom
    accent: custom

extra_css:
  - stylesheets/extra.css

nav:
  - Introduction: index.md
  - Repository: repository.md
  - Contact List: contact-list.md
  - Organization: organization.md
  - Project: project.md
  - Service Queue: service-queue.md
  
